# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0002_on_delete'),
        ('tagging', '0002_add_lang_fields'),
    ]

    operations = [
    ]
